# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zag3m PD2 imaginary patch notes
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An awesome description.
# baseurl: "/docs" # the subpath of your site, e.g. /blog
github_username:  zagd3m

# User defined
domain: zagd3m.github.io
url: https://zagd3m.github.io
baseurl: /patchnotes

# Github not modifiable
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-google_search_console_verification_file

google_search_console:
  verification_file_code: tVVubyU7ZsnZzqiGMR1LI8gw1Muo7pVXZs-wACE2fnU

sass:
  sass_dir: _sass
  style: compressed

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

relative_links:
  enabled:     true
  collections: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
